sandbox/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from test_db import urls as testdb_urls


urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include(testdb_urls)),
    path('admin/', admin.site.urls),
]

src/htmx_viewsets/forms.py
from collections import OrderedDict

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.http.request import HttpRequest


class GroupByForm(forms.Form):
    group_by = forms.ChoiceField(label=_('Gruppieren nach'), required=False)

    def __init__(self, request, lookups):
        assert isinstance(request, HttpRequest)
        super().__init__(request.GET)
        self.fields['group_by'].choices = self.get_group_by_choices(lookups)

    def get_group_by_choices(self, lookups):
        choices = [['', _('Bitte auswählen')]]
        for name, verbose_name in lookups:
            choices.append((name, verbose_name))
        return choices

    def group_qs_by(self, qs):
        group_by = self.cleaned_data.get('group_by', None)
        return qs.values(group_by).order_by(group_by)

    def clean(self):
        data = super().clean()
        if data.get('group_by', None) == '':
            del data['group_by']
        return data


class AddFilterForm(forms.Form):
    x__type = forms.ChoiceField(
        label='Art',
        choices=[
            ['f', _('Einbezogen (filter)')],
            ['e', _('Ausgenommen (exclude)')],
        ]
    )
    x__lookup = forms.ChoiceField(label=_('Eigenschaft'))
    x__value = forms.CharField(label=_('Wert'))

    def __init__(self, request, lookups):
        assert isinstance(request, HttpRequest)
        if request.method == 'POST':
            super().__init__(request.POST)
        else:
            super().__init__()
        self.fields['x__lookup'].choices = self.get_lookup_choices(lookups)

    def get_lookup_choices(self, lookups):
        lookup_choices = [('', _('Bitte auswählen'))]
        for name, verbose_name in lookups:
            lookup_choices.append((name, verbose_name))
        return lookup_choices

    def clean(self):
        data = super().clean()
        if not all((data.get('x__type', False), data.get('x__lookup', False))):
            raise ValidationError('No valid lookup')
        key = f'{data["x__type"]}__{data["x__lookup"]}'
        return {key: data["x__value"]}


class FilterLookup:
    def __init__(self, key, value):
        self.key = key
        self.name = key.split('__', 1)[1]
        self.value = value
        self.bg_class = {
            'f': 'success',
            'e': 'danger'
        }.get(key.split('__', 1)[0])


class FilterForm(forms.Form):
    method = 'GET'

    def __init__(self, request, lookups):
        super().__init__(getattr(request, self.method))
        self.fields = self.get_form_fields(lookups)
        if self.is_valid():
            self.enabled_lookups = self.get_enabled_lookups()

    def get_enabled_lookups(self):
        lookups = []
        for key, value in self.cleaned_data.items():
            lookups.append(FilterLookup(key, value))
        return lookups

    def get_form_fields(self, lookups):
        fields = OrderedDict()
        for name, verbose_name in lookups:
            field = forms.CharField()
            field.name = name
            field.verbose_name = verbose_name
            field.required = False
            fields[f'f__{name}'] = field
            fields[f'e__{name}'] = field
        return fields

    def filter_qs(self, qs):
        """
        Todo: Handle multiple filters with same lookup (OR'ed)
        """
        for key, value in self.cleaned_data.items():
            method_code, lookup = key.split('__', 1)
            method = {'f': 'filter', 'e': 'exclude'}[method_code]
            qs = getattr(qs, method)(**{lookup: value})
        return qs

    def clean(self):
        data = super().clean()
        return {key: value for key, value in data.items() if key in self.data}


class RemoveFilterForm(FilterForm):
    method = 'POST'

    def clean(self):
        data = super().clean()
        delete_fields = {}
        if data.get('delete_method_lookup', False):
            method_lookup, value = data['delete_method_lookup'].split('=')
            field = self.fields[method_lookup]
            field.validate(value)
            delete_fields[method_lookup] = value
        return delete_fields

src/htmx_viewsets/views.py
from typing import Iterable, Optional, Dict, TYPE_CHECKING, Any, List, Callable
from collections import OrderedDict
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db import models
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http.response import JsonResponse, HttpResponse
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View
from django import forms
from django.http.request import HttpRequest
from django.db.models.query import QuerySet
from django.shortcuts import redirect, reverse
from .chart import ChartBase


class CloseModalResponse:
    def __new__(cls) -> HttpResponse:
        msg = "<script>$(function(){$('#modal').modal('hide');})</script>"
        return HttpResponse(msg)


class RefreshDataTableResponse:
    def __new__(cls, table_id: str) -> HttpResponse:
        msg = f"""
            <script>
                $(function(){{
                    reload_table("{table_id}");
                    $('#modal').modal('hide');
                }})
            </script>
        """
        return HttpResponse(msg)


class HtmxView(ContextMixin, View):
    pass


class ViewResponse:
    def __new__(cls, view_class:View, request:HttpRequest, method:str='get',
                **kwargs:Optional[Any]) -> HttpResponse:
        view = view_class(**kwargs)
        return getattr(view, method)(request)


class HtmxModelView(HtmxView, TemplateResponseMixin, ContextMixin):
    # Is set from viewset if this is a viewset view:
    code:               str
    model: models.Model = None
    fields:             Iterable[str]
    prefetch_related:   Iterable[str] = []
    select_related:     Iterable[str] = []

    # Later: permission_required:Iterable[Permission] = []
    #url_names:          Dict[str, str] = {}

    template_name:      str = 'htmx_viewsets/form.html'
    object:             models.Model
    node_id: str
    viewset_class: 'viewsets.HtmxViewSetBase'
    viewset: 'viewsets.HtmxViewSetBase'
    model: models.Model
    base_queryset: QuerySet
    queryset: QuerySet

    url_names: Dict
    url_name: str

    chart_class: ChartBase

    def __new__(cls):
        setattr(cls, 'url_names', cls.viewset_class.url_names)
        return ContextMixin.__new__(cls)

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return self.handle_no_permission()
        self.viewset = self.viewset_class(request)
        self.fields = self.get_fields()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.viewset.get_queryset()

    def get_fields(self):
        qs = self.get_queryset()
        model_fields = [field.name for field in qs.query.get_meta().fields 
                        if not field.primary_key]
        viewset_fields = [field.name for field in self.viewset.viewset_fields]
        return [model_field for model_field in model_fields 
                if model_field in viewset_fields]

    def get_success_url(self) -> Any:
        if self.object:
            self.object.refresh_from_db()
            if self.object:
                return reverse(
                    self.url_names['detail'], kwargs={'pk': self.object.pk})
        return reverse(self.url_names['list'])

    def get_context_data(self, *args:Optional[Any], **kwargs:Optional[Any]) -> Dict[str, Any]:
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update(self.viewset.get_context_data())
        ctx['field_values'] = self.get_field_values()
        ctx['next_url'] = self.get_next_url()
        return ctx

    def get_field_values(self) -> Optional[OrderedDict]:
        if hasattr(self, 'object') and self.object:
            row = self.viewset.table.get_row(self.object)
            values = [(cell.verbose_name, cell.render()) for cell in row.cells]
            return OrderedDict(values)

    def get_next_url(self) -> Any:
        method = self.request.method
        kwargs = getattr(self.request, method)
        return kwargs.get('next', reverse(self.url_names['list']))


class HtmxListView(HtmxModelView, ListView):
    template_name = 'htmx_viewsets/list.html'
    code = 'list'
    force_full = True
    methods = ['get', 'post']

    def post(self, request:HttpRequest, *args:Optional[Any], **kwargs:Optional[Any]):
        request_get = request.GET.copy()

        form = self.viewset.add_filter_form
        if form.is_valid():
            request_get.update(form.cleaned_data)

        form = self.viewset.remove_filter_form
        if form.is_valid():
            for key in form.cleaned_data.keys():
                request_get.pop(key)

        form = self.viewset.group_by_form
        request_get.pop('group_by', None)
        if form.is_valid():
            request_get.update(form.cleaned_data)

        return redirect(f'{request.path}?{request_get.urlencode()}')

    def get_context_data(self, *args:Optional[Any], **kwargs:Optional[Any])->Dict[str, Any]:
        ctx = super().get_context_data(*args, **kwargs)
        ctx.pop('next_url', None)
        return ctx


class HtmxTableView(HtmxModelView, ListView):
    template_name = ''
    code = 'table'

    def get(self, request:HttpRequest, *args:Optional[Any], **kwargs:Optional[Any]) -> JsonResponse:
        return JsonResponse(self.viewset.table.data)

    def post(self, request:HttpRequest, *args:Optional[Any], **kwargs:Optional[Any]) -> JsonResponse:
        return self.get(request, *args, **kwargs)


class HtmxDetailView(HtmxModelView, DetailView):
    template_name = 'htmx_viewsets/detail.html'
    code = 'detail'


class HtmxCreateView(HtmxModelView, CreateView):
    http_method_names = ['get', 'post']
    code = 'create'


class HtmxUpdateView(HtmxModelView, UpdateView):
    http_method_names = ['get', 'post']
    code = 'update'

    def get_context_data(self, *args:Optional[Any], **kwargs:Optional[Any])->Dict[str, Any]:
        ctx = super().get_context_data(*args, **kwargs)
        ctx['form'] = self.get_form()
        ctx['next_url'] = self.get_next_url()
        ctx['object'] = self.get_object()
        return ctx


class HtmxDeleteView(HtmxModelView, DeleteView):
    template_name = 'htmx_viewsets/delete.html'
    http_method_names = ['get', 'post']
    code = 'delete'

    def get_context_data(self, *args:Optional[Any], **kwargs:Optional[Any])->Dict[str, Any]:
        ctx = super().get_context_data(*args, **kwargs)
        ctx['next_url'] = self.get_next_url()
        return ctx

    def form_valid(self, form: forms.Form) -> HttpResponse:
        super().form_valid(form)
        if self.request.htmx:
            return RefreshDataTableResponse(self.viewset.table.table_id)
        return redirect(self.get_next_url())


class HtmxChartDataView(HtmxModelView, ListView):
    code            : str = 'chart'
    charts          : List['chart.ChartBase']
    template_name = ''

    def get(self, request:HttpRequest, *args:Optional[Any], **kwargs:Optional[Any]) -> JsonResponse:
        return JsonResponse({'data': self.viewset.chart.data})

src/htmx_viewsets/templates/htmx_viewsets/chart.html
<div>
  <canvas id="chart_{{ chart.chart_id }}"></canvas>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const ctx = document.getElementById('chart_{{ chart.chart_id }}');
  const chart = new Chart(ctx, {{ chart.config_json|safe }});
  $.ajax({
	  url: '{% url chart.url %}?{{ get_kwargs|safe }}',
	  type: 'GET',
	  success: function (response) {
		  chart.data = response.data;
		  chart.update();
	  }
  })
</script>

src/htmx_viewsets/templates/htmx_viewsets/delete.html
{% extends './dispatch.html' %}
{% load i18n %}


  {% block modal_title %}
      {{ verbose_name }}: {{ object }} {% trans 'Löschen?' %}
  {% endblock modal_title %}
  
  {% block modal_body %}
    {% blocktranslate %}Möchten Sie '{{ object }}' wirklich löschen?{% endblocktranslate %}
    <form id="modal-form" hx-boost="true" hx-swap="outerHTML" hx-target="#to-execute" hx-push-url="false" action="{{ target_url }}" method="POST">{% csrf_token %}
        {{ form.as_table }}
    </form>
  {% endblock modal_body %}
  
  {% block modal_submit_button %}
    <button id="modal-delete-button" type="submit" class="btn btn-primary" form="modal-form" data-dismiss="modal" aria-label="Close">
      {% trans 'Löschen' %}
    </button>
    <script id="to-execute">
    </script>
  {% endblock modal_submit_button %}

src/htmx_viewsets/templates/htmx_viewsets/detail.html
{% extends './dispatch.html' %}

{% block modal_title %}
  {{ verbose_name }}: {{ object }}
{% endblock modal_title %}

{% block modal_body %}
  <table class="table">
    <tbody>
      {% for key, value in field_values.items %}
        <tr>
          <th scope="row">{{ key }}</th>
          <td>{{ value|safe }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock modal_body %}

src/htmx_viewsets/templates/htmx_viewsets/dispatch.html
{% extends request.htmx|yesno:dispatch_template %}
{% load i18n %}


{% block main %}
  {% block htmx_main %}
    <h1>{% block modal_title %}{% endblock modal_title %}</h1>
    {% block modal_body %}{{block.super}}{% endblock %}
    {{block.super}}
    <div class="btn-group" role="group" aria-label="Basic example">
      {% block modal_submit_button %}{% endblock modal_submit_button %}
      {% if next_url %}
        <a class="btn btn-secondary modal-close-button ml-3" href="{{ next_url }}">{% trans 'Abbrechen' %}</a>
      {% endif %}
    </div>
  {% endblock %}
{% endblock %}

src/htmx_viewsets/templates/htmx_viewsets/form.html
{% extends './dispatch.html' %}
{% load i18n %}


{% block modal_title %}
  {{ verbose_name }}: {{ object }}
{% endblock modal_title %}


{% block modal_body %}
  <style>
    #modal-form input, #modal-form textarea, #modal-form select{width: 100%;}
  </style>
  <form id="modal-form" hx-boost="true" hx-swap="none" hx-push-url="false" action="{{ target_url }}" method="POST" enctype="multipart/form-data" hx-encoding="multipart/form-data">{% csrf_token %}
    <table class="w-100">
      {{ form.as_table }}
    </table>
  </form>
{% endblock %}


{% block modal_submit_button %}
  <button type="submit" hx-boost="true" hx-swap="none" hx-push-url="false" class="btn btn-primary" form="modal-form" autofocus>
    {% trans 'Speichern' %}
  </button>
{% endblock modal_submit_button %}

src/htmx_viewsets/templates/htmx_viewsets/full.html
{% load htmx_viewsets %}
<html>
  <head>
    {% htmx_viewsets_static_all %}
  </head>
  <body>
    <div class="container">
      {% block main %}{% endblock main %}
      {% htmx_viewsets_fixed_content %}
    </div>
  </body>
</html>

src/htmx_viewsets/templates/htmx_viewsets/list.html
{% extends './dispatch.html' %}
{% load i18n %}

{% block htmx_main %}
<div class="row mt-3">
  <div class="col-12">
    <h2>{{ verbose_name_plural }}</h2>
  </div>
  <form method="POST" action="{{ request.path }}?{{ request.GET.urlencode }}">{% csrf_token %}
    {% if enabled_filter_form.enabled_lookups %}
      <div class="row mt-3">
        <div class="col-auto">
          <span class="badge badge-light text-bg-light">
            Filter entfernen:
          </span>
        </div>
        {% for lookup in enabled_filter_form.enabled_lookups %}
          <div class="col-auto">
            <button type="submit" class="btn btn-{{ lookup.bg_class }} btn-sm p-0" name="delete_method_lookup" value="{{ lookup.key }}={{ lookup.value }}">
              <span class="badge">
                {{ lookup.name }}={{ lookup.value }}
              </span>
            </button>
          </div>
        {% endfor %}
        <div class="row">
          <div class="col-12">
            <hr>
          </div>
        </div>
      </div>
    {% endif %}
  </form>
  <div class="row">
    <div class="col-12">
      <button class="btn btn-link text-decoration-none" type="button" data-bs-toggle="collapse" data-bs-target="#add-filter-form" aria-expanded="false" aria-controls="add-filter-form">
        &#43; Filter hinzufügen
      </button>
      <div>
        <div class="collapse" id="add-filter-form">
          <div class="card card-body w-100">
            <form id="add-filter-argument-form" method="POST" action="{{ request.path }}?{{ request.GET.urlencode }}">{% csrf_token %}
              <table class="w-100">
                {{ add_filter_form.as_table }}
                <tr>
                  <td>
                  </td>
                  <td>
                    <button class="btn btn-primary" type="submit">Filter hinzufügen</button>
                    <button class="btn btn-secondary" type="reset">Zurücksetzen</button>
                  </td>
                </tr>
              </table>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% if chart %}
<div class="row">
  <div class="col-12">
    <hr>
  </div>
  <form id="group-by-form" method=GET action="{{ request.path }}?{{ request.GET.urlencode }}">
    <div class="col-12">
      <table>
        {{ group_by_form.as_table }}
      </table>
    </div>
  </form>
</div>
  <div class="row">
    <div class="col-12">
      {% include './chart.html' %}
    </div>
  </div>
  <div class="col-12">
    <hr>
  </div>
{% endif %}
<div class="row mt-3">
  <div class="col-12 mb-3">
    <a class="btn btn-link text-decoration-none" href="{% url create_url %}" hx-get="{% url create_url %}" hx-swap="none">&#43; {% trans 'Erstelle' %} {{ verbose_name }}</a>
  </div>
  <div class="col-12">
    <div class="table-responsive">
      {% include table %}{{ table_id }}
    </div>
  </div>
</div>
<style>
  #id_x__value{width: 100%;}
  #add-filter-argument-form .select2-container{width: 100%!important;}
</style>
<script>
    htmx.onLoad(function() {
      $('.modal-close-button').on('click', function () {
          $('#modal').modal('hide');
      });
    });
	$('#id_x__type').select2({});
	$('#id_x__lookup').select2({});
	$('#id_group_by').select2({});
	$('#id_group_by').change(function(){
		$('#group-by-form').submit();
	});
</script>
{% endblock %}

src/htmx_viewsets/templates/htmx_viewsets/modal.html
{% load i18n %}


<div id="modal-content" hx-swap="innerHTML" hx-swap-oob=true class="modal-content">
  {% block modal_content %}
    <div id="modal-header" class="modal-header">
      {% block modal_header %}
        <h5 class="modal-title" class="modal-title">
          {% block modal_title %}{{ modal_title }}{% endblock modal_title %}
        </h5>
        {% block modal_close_button %}
          {% if request.htmx %}
            <button class="btn modal-close-button" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          {% endif %}
        {% endblock modal_close_button %}
      {% endblock modal_header %}
    </div>
    <div id="modal-body" class="modal-body">
      {% block modal_body_pre %}{{ modal_body_pre }}{% endblock modal_body_pre %}
      {% block modal_body %}{{ modal_body }}{% endblock modal_body %}
      {% block modal_body_post %}{{ modal_body_post }}{% endblock modal_body_post %}
    </div>
    <div id="modal-footer" class="modal-footer">
      {% block modal_footer %}
        {{ modal_footer }}
        {% block modal_submit_button %}{% endblock modal_submit_button %}
        <button type="button" class="btn btn-secondary modal-close-button" data-dismiss="modal">{% trans 'Schließen' %}</button>
      {% endblock modal_footer %}
    </div>
  {% endblock modal_content %}
  {% block modal_scripts_wrapper %}
    <script>
    	$(function(){
  			$('#modal').modal('show');
    		{% block modal_scripts %}{% endblock modal_scripts %}
    	})
    </script>
  {% endblock modal_scripts_wrapper %}
</div>

src/htmx_viewsets/templates/htmx_viewsets/partial.html
{% extends './modal.html' %}


{% block modal_close_button %}
    {% if request.htmx %}
      {{ block.super}}
    {% elif next_url %}
      <a href="{{ next_url}}" class="btn btn-link" style="text-decoration: unset;" hx-get="{{ next_url }}" hx-swap="none" hx-push-url="true">
        <i class="fa-solid fa-angles-left"></i> Zurück
      </a>
    {% endif %}
{% endblock %}


{% block modal_body %}
  <div>
    {% block main %}{% endblock %}
  </div>
{% endblock %}


{% block modal_footer1 %}
  {% if request.htmx %}
    <button type="button" class="btn btn-secondary modal-close-button" data-dismiss="modal">Schließen</button>
  {% elif next_url %}
    <a href="{{ next_url}}" class="btn btn-secondary modal-close-button" data-dismiss="modal" hx-get="{{ next_url }}" hx-swap="none" hx-push-url="true">Schließen</a>
  {% endif %}
{% endblock modal_footer1 %}

src/htmx_viewsets/templates/htmx_viewsets/table.html
<table id="{{ table.table_id|safe }}" class="{{ table.table_classes|safe }}" style="{{ table.styles|safe }}">
    <thead>
        <tr>
          {% for column in table.columns %}
            <th style="color: {{ column.field.color }}">{{ column }}</th>
          {% endfor %}
        </tr>
    </thead>
    {% if not table.ajax_url %}
      <tbody>
        {% for row in table.rows %}
          <tr>
            {% for cell in row.cells %}
              <td class="text-truncate">
                {{ cell }}
              </td>
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    {% endif %}
    {% if table.show_footer %}
      <tfoot>
          <tr>
            {% if False and table.row_action_classes %}
              <th></th>
            {% endif %}
            {% for column in table.columns %}
              <th>{{ column }}</th>
            {% endfor %}
          </tr>
      </tfoot>
    {% endif %}
</table>
<script>
    function reload_table(table_id){
        var table = $('#' + table_id).DataTable();
        table.ajax.reload(null, false);
    }
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
	$(document).ready( function () {
        const csrftoken = getCookie('csrftoken');

		var table = $('#{{ table.table_id|safe }}').DataTable({
			lengthMenu: {{ table.length_menu|safe }},
			stateSave: true,
			responsive: true,
			autoWidth: false,
			language: {
				"emptyTable": "Keine Daten in der Tabelle vorhanden",
				"info": "_START_ bis _END_ von _TOTAL_ Einträgen",
				"infoEmpty": "0 bis 0 von 0 Einträgen",
				"infoFiltered": "(gefiltert von _MAX_ Einträgen)",
				"infoThousands": ".",
				"lengthMenu": "_MENU_ Einträge anzeigen",
				"loadingRecords": "Wird geladen...",
				"processing": "Bitte warten...",
				"search": "Suchen",
				"zeroRecords": "Keine Einträge vorhanden.",
				"paginate": {
	  				"first": "Erste",
  					"previous": "Zurück",
    				"next": "Nächste",
    				"last": "Letzte",
				},
				"aria": {
					"sortAscending": ": aktivieren, um Spalte aufsteigend zu sortieren",
					"sortDescending": ": aktivieren, um Spalte absteigend zu sortieren",
				},
	        },
			{% if table.row_action_classes %}
	        columnDefs: [
            	{ orderable: false, targets: 0 }
            ],
			{% endif %}

			{% if table.ajax_url %}
  	        serverSide: true,
			ajax: {
  				url: '{{ table.ajax_url|safe }}',
  				type: "POST",
  				dataSrc: 'data',
  				headers: {'X-CSRFToken': csrftoken},
			},
			{% endif %}
		});
		htmx.onLoad(function(){
			reload_table('{{ table.table_id|safe }}');
		})
		table.on('draw', function ( e, settings, json, xhr ) {
			htmx.process('#{{ table.table_id|safe }}');
        })

	});
</script>